#let colophon-page(edition, profile) = {
  pagebreak()

  line(length: 100%)
  v(1em)

  text(size: 0.85em, fill: luma(100))[
    Generated by *Lemonade* · #edition.at("edition_date", default: "")

    #if "metadata" in edition {
      let meta = edition.metadata
      if "sources_count" in meta {
        [Sources: #meta.sources_count.at("rss", default: 0) RSS, #meta.sources_count.at("youtube", default: 0) YouTube]
      }
    }
  ]
}
